// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RtaPN_A5oJhpTsljBljNofZvGETHLBI',
    appId: '1:911519797959:web:f5245013ee07f4159fe4e2',
    messagingSenderId: '911519797959',
    projectId: 'qari-app-ee702',
    authDomain: 'qari-app-ee702.firebaseapp.com',
    storageBucket: 'qari-app-ee702.firebasestorage.app',
    measurementId: 'G-HZ4SCGM83G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDooq6Vr6z1lYgd25K1HfgyGuEYH2YTpHA',
    appId: '1:911519797959:android:6ab71a22b8055c689fe4e2',
    messagingSenderId: '911519797959',
    projectId: 'qari-app-ee702',
    storageBucket: 'qari-app-ee702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWND3pL7XRNH0j-0yE9Qxqi4kEZLFxHQs',
    appId: '1:911519797959:ios:1d6fa690ffa7c6f39fe4e2',
    messagingSenderId: '911519797959',
    projectId: 'qari-app-ee702',
    storageBucket: 'qari-app-ee702.firebasestorage.app',
    iosBundleId: 'com.example.qari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWND3pL7XRNH0j-0yE9Qxqi4kEZLFxHQs',
    appId: '1:911519797959:ios:1d6fa690ffa7c6f39fe4e2',
    messagingSenderId: '911519797959',
    projectId: 'qari-app-ee702',
    storageBucket: 'qari-app-ee702.firebasestorage.app',
    iosBundleId: 'com.example.qari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RtaPN_A5oJhpTsljBljNofZvGETHLBI',
    appId: '1:911519797959:web:7b201c7c902b3a979fe4e2',
    messagingSenderId: '911519797959',
    projectId: 'qari-app-ee702',
    authDomain: 'qari-app-ee702.firebaseapp.com',
    storageBucket: 'qari-app-ee702.firebasestorage.app',
    measurementId: 'G-E8QG2MD572',
  );
}
