import sys
import os

# Add project root to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text
from app.database import SessionLocal

def main():
    db = SessionLocal()
    # Values to add to the notificationtype enum
    new_types = [
        "admin_user_registered",
        "admin_user_deleted",
        "admin_community_created",
        "admin_premium_purchased",
        "admin_feature_request",
        "new_book_added"
    ]
    
    try:
        # Check existing values in the enum to avoid "already exists" errors
        # Note: In PostgreSQL, 'notificationtype' is likely the name if it was generated by SQLAlchemy
        result = db.execute(text("SELECT enumlabel FROM pg_enum JOIN pg_type ON pg_enum.enumtypid = pg_type.oid WHERE pg_type.typname = 'notificationtype';"))
        existing_types = [row[0] for row in result]
        
        # PostgreSQL doesn't allow ALTER TYPE ... ADD VALUE inside a transaction block easily in some versions/drivers
        # We need to run each one separately and commit if possible, or use autocommit
        
        # We'll try to run them individually
        for n_type in new_types:
            if n_type not in existing_types:
                print(f"Adding {n_type} to notificationtype enum...")
                # We use execution_options(autocommit=True) if supported, or just run it
                # ALTER TYPE cannot be run in a multi-statement transaction in some PG versions
                db.execute(text(f"ALTER TYPE notificationtype ADD VALUE '{n_type}';"))
                db.commit()
                print(f"Successfully added {n_type}.")
            else:
                print(f"{n_type} already exists in enum.")
                
        print("Enum update complete.")
    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    main()
